language: cpp
script: 
  - mkdir build && cd build
  - CPPUTEST_HOME=~/cpputest/ cmake .. -DCOMPILE_TESTS=ON
  - make
compiler:
  - clang
  - gcc
dist: trusty
addons:
  apt:
    packages:
    - cmake
    - libevent-dev
    - libconfig++-dev

before_install:
    # Install CppUTest
    - export CPPUTEST_VERSION=3.8
    - export CPPUTEST=cpputest-${CPPUTEST_VERSION}
    - wget https://github.com/cpputest/cpputest/releases/download/v${CPPUTEST_VERSION}/${CPPUTEST}.tar.gz
    - tar -xzvf *.tar.gz
    - cd ${CPPUTEST}
    - mkdir _build && cd _build
    - cmake -DC++11=ON -DTESTS=OFF -DCMAKE_INSTALL_PREFIX:PATH=~/cpputest/ ..
    - make && make install && cd ../..
